### ISSUE TITLE
Exception Handling: IllegalArgumentException

### ISSUE THREAD

**Issue by Flashky** [Flashky/notifier-packt#8]
There is at least one known case of throwing``IllegalArgumentException``:

```java
java.lang.IllegalArgumentException: Malformed URL: htttps://www.packtpub.com/packt/offers/free-learning
	at org.jsoup.helper.HttpConnection.url(HttpConnection.java:136)
	at org.jsoup.helper.HttpConnection.connect(HttpConnection.java:76)
	at org.jsoup.Jsoup.connect(Jsoup.java:73) 
       [...]
Caused by: java.net.MalformedURLException: unknown protocol: htttps
	at java.net.URL.<init>(URL.java:600)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at org.jsoup.helper.HttpConnection.url(HttpConnection.java:134)
```
In this case, the IllegalArgumentException is caused by MalformedURLException.

The handler should:

1. Log the exception message as error.
2. Log the cause message as error.
3. Log the exception trace on a different error file.
4. Terminate the program.

**Comment by Flashky** [comment]
Won't be done for now.
